---
jobs:
- name: job-unit-testing
  public: true
  serial: true
  plan:
  - get: resource-todo-app
    trigger: true
  - task: php-test-web-app
    config:
      params:
        TEST_TOKEN: {{TEST-TOKEN}}
    file: resource-todo-app/ci/task/run-test.yml



- name: deploy-to-pws
  public: true
  serial: true
  plan:
  - get: resource-todo-app
    trigger: true
    passed: [job-unit-testing]
  - put: deploy-to-pws
    params:
      manifest: resource-todo-app/manifest.yml
      path: resource-todo-app/
      current_app_name: todo-apps-ge 

resources:

- name: resource-todo-app
  type: git
  source:
    uri: https://github.com/ymakihar/todo-apps-php-cf.git
    branch: feature/adding_concourse_pipeline


- name: deploy-to-pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{pws-username}}
    password: {{pws-password}}
    organization: {{pws-org}}
    space: {{pws-space}}
    skip_cert_check: false
